<?php echo Core::getTemplate('header'); ?>

<!-- ~~~Content~~~ -->
<div id="content">

    <h1>AppCore</h1>

    <p>AppCore is a micro-PHP framework primarily built around a single file God class. The framework includes some of the following features:</p>

    <ul>
        <li>Simplicity - Develop small lightweight apps quickly with little bloat</li>
        <li>Basic URL Routing - Automatically route URLs to controllers and actions, or to simple templates for content</li>
        <li>Singleton Class Factory - Autoload and instantiate classes with data persistence over multiple references at runtime</li>
        <li>SimpleXML Configuration - Store config values in a single XML file and easily retrieve those values</li>
    </ul>

    <p>This framework is the result of my own personal tinkering and I have used it to underpin several projects. While I maintain copyright it is free for use however you may wish. Contributions and suggestions are welcome.</p>

</div>

<?php echo Core::getTemplate('footer'); ?>
